In [1]:
import pandas as pd
import random
from SoundsLike.SoundsLike import Search

## Import unique_people dataset

In [2]:
data = pd.read_csv('unique_people_transactions.csv')
data.head()

,transaction_id,sender_name,receiver_name,sender_address_full,sender_zipcode,receiver_address_full,receiver_zipcode,transaction_amount
0,1,Brianna Smith,James Bailey Collins,United States,NaN,"Wisconsin, LU",12572.0,639426.80
1,2,Michelle Lawson,Brian Yang,"5949 Christine Extension, Bobbyville, PW 91044",NaN,"Arkansas, CU",423.0,25010.76
2,3,Nathan Morrow,Mitchell Michele Cowan,NaN,69908,"1719 Allen Crossroad Apt. 183, Simmonsside, ID...",599.0,275029.32
3,4,Michael Sandra Duarte,Carla Allen,Kiribati,NaN,MK,22965.0,223210.74
4,5,Kyle Victor Kelly,Stephanie Erin West,Saint Vincent and the Grenadines,NaN,"778 Joseph Corners Suite 596, Jeremiahfurt, NE...",78115.0,736471.21

In [3]:
def initials(name, name_part):
    names = name.split(' ')
    if name_part == "first":
        names[0] = names[0][0]
    elif name_part == "last":
        names[-1] = names[-1][0]
    else:
        for i in range(len(names)):
            if i != 0 and i != len(names) - 1:
                names[i] = names[i][0]
    return " ".join(names)

In [4]:
print(initials("Ian Lewis Thornton Reinert", "first"))
print(initials("Ian Lewis Thornton Reinert", "last"))
print(initials("Ian Lewis Thornton Reinert", "middle"))

I Lewis Thornton Reinert
Ian Lewis Thornton R
Ian L T Reinert

In [5]:
def alter_name(name, add_char, name_part):
    names = name.split(' ')
    if name_part == "first":
        names[0] += add_char
    elif name_part == "last":
        names[-1] += add_char
    else:
        for i in range(len(names)):
            if i != 0 and i != len(names) - 1:
                names[i] += add_char
    return " ".join(names)

In [6]:
print(alter_name("Ian Lewis Thornton Reinert", "e", "first"))
print(alter_name("Ian Lewis Thornton Reinert", "e", "last"))
print(alter_name("Ian Lewis Thornton Reinert", "e", "middle"))

Iane Lewis Thornton Reinert
Ian Lewis Thornton Reinerte
Ian Lewise Thorntone Reinert

In [7]:
def homophone(name, name_part):
    names = name.split(' ')
    if name_part == "first":
        homophones = Search.perfectHomophones(names[0])
        if len(homophones) > 0:
            names[0] = homophones[0]
        else:
            names[0] = Search.closeHomophones(names[0])[0]
    elif name_part == "last":
        homophones = Search.perfectHomophones(names[-1])
        if len(homophones) > 0:
            names[-1] = homophones[0]
        else:
            names[-1] = Search.closeHomophones(names[0])[0]
    else:
        for i in range(len(names)):
            if i != 0 and i != len(names) - 1:
                homophones = Search.perfectHomophones(names[i])
                if len(homophones) > 0:
                    names[i] = homophones[0]
                else:
                    names[i] = Search.closeHomophones(names[0])[0]
                    
    return " ".join(names)

In [24]:
print(homophone("Ian Thornton Reinert", "first"))
print(homophone("Jimmy Zhu", "first"))
print(homophone("Ian Thornton Reinert", "middle"))

Ian Thornton Reinert
Jimi Zhu
Ian Thornton Reinert

In [38]:
Search.closeHomophones("Reinert")

['Reinert']

In [9]:
name = "Reinert"
listed = []
try:
    listed = Search.closeHomophones("Reinart")
except ValueError:
    print(f'{name} not available in homophone dictionary')
print(listed)

Reinert not available in homophone dictionary
[]

In [10]:
import random
def add_suffix(name):
    suffixes = ["Jr", "Sr", "I", "II", "III",]
    name += " " + random.choice(suffixes)
    
    return name

In [11]:
print(add_suffix("Ian Thornton Reinert"))
print(add_suffix("Ian Thornton Reinert"))
print(add_suffix("Ian Thornton Reinert"))

Ian Thornton Reinert II
Ian Thornton Reinert III
Ian Thornton Reinert III

In [12]:
df = pd.read_csv("unique_people_transactions.csv")

In [15]:
import edge_cases as ec

test = ec.create_middle_initial_dataset(df, 0.05)

Dataset created and saved as middle_initial.csv

In [17]:
len(test)

50

In [18]:
new_df = test.loc[test['sender_name'].apply(lambda x: len(x.split(' '))) > 2]

In [19]:
new_df.tail(100)

,transaction_id,sender_name,receiver_name,sender_address_full,sender_zipcode,receiver_address_full,receiver_zipcode,transaction_amount
814,815,Thomas Anthony Clark,Sydney Natalie Gomez,United States,NaN,ZM,2231.0,45990.97
817,818,Kimberly Charles Martinez,Melissa Ashley Holmes,United States,NaN,"Unit 9650 Box 7362, DPO AP 25171",781.0,374841.09
818,819,Carl James Wilson,Heather Carla Williamson,NaN,xx,"57010 Charles Route Suite 372, South Seth, SC ...",406.0,145569.80
819,820,Amber Lindsay Turner,Jamie Denise Sandoval John,United States,82603,"Idaho, PS",35001.0,531166.32
822,823,Stephen Roberta Francis,Nicole Devin Holland,United States,74165,"662 Debra Drive Suite 961, Thomasberg, OR 11282",50767.0,169983.65
...,...,...,...,...,...,...,...,...
990,991,M Amanda Cochran,James Phillips,United States,NaN,"593 Ruth Villages, New Jay, VI 26626",68823.0,414884.53
992,993,A Diana Hicks,Catherine Flores,Australia,37019,"16730 Soto Mountain Apt. 429, Port Rickport, M...",798.0,489347.04
995,996,A Joshua Cowan,April Hall,Benin,NaN,"5789 Peterson Run, Suzanneview, VT 91610",427.0,32716.29
996,997,J Jacqueline Owen,Kevin Becker DVM,United States,NaN,"64122 James Glens, New George, PW 31513",186.0,370529.96
999,1000,J Timothy Dunn,Kristen Harrington,Christmas Island,NaN,"0160 Joseph Locks, South Mathewmouth, VI 10151",67289.0,855450.19

In [29]:
new_df = test.loc[test['sender_name'].apply(lambda x: homophone(x, 'first')) != test['sender_name']]

In [30]:
new_df

,transaction_id,sender_name,receiver_name,sender_address_full,sender_zipcode,receiver_address_full,receiver_zipcode,transaction_amount
1,913,Jonathan J Ramirez,Bianca Suarez,United States,NaN,"13412 Wilson Brooks, Gabrielfurt, NM 15770",796.0,286194.15
10,929,Steven C Brandt,Cindy Debbie Hicks,United States,NaN,"Unit 6099 Box 0231, DPO AP 30003",851.0,732359.77
11,933,Gary M Perez,Samantha Randy Jones,United States,NaN,"4557 Schmidt Passage Suite 746, North Alvinbor...",54033.0,175640.07
12,934,Christy J Valentine,Lisa Robinson,"9792 Pierce Track Suite 365, Lake Sandra, UT 4...",NaN,"1173 Alfred Centers Apt. 919, Glenchester, NM ...",20899.0,132159.80
14,937,Tammy S Lin,Elizabeth Danielle Hodge,United States,NaN,"86103 Brian Views, Byrdland, TN 70979",10488.0,530852.37
16,942,Sylvia C Miranda,Haley Gutierrez,NaN,xx,"4088 Armstrong Stravenue, Kimberlyborough, NC ...",89558.0,481847.83
18,946,Mrs. B Ingram,Lisa Williams,"566 Heather Burgs Apt. 264, South Victorberg, ...",70731,"9833 Jarvis Summit Apt. 716, North Lesliestad,...",241.0,115169.71
25,959,Kyle T Freeman,Julie Johnson,"621 Wilkerson Lane, Lake Tammy, NH 96605",NaN,"3014 Nelson Inlet, Larryton, RI 71639",843.0,454786.03
28,965,Cody C Ellison,Donna Anthony Smith,Mali,NaN,"6183 Bush Ford, Jacquelinehaven, KY 08856",30156.0,108346.10
30,969,Keith L Nelson,Jerry Coleman,United States,NaN,"81085 Carlos Shoal Suite 056, Jonathanbury, MO...",35828.0,561407.38
31,970,Allison R Freeman,Megan Laura Lopez,France,NaN,"7925 Erickson Estate, Santosstad, MI 48519",900.0,915255.91
32,971,Kelly S Hart,Scott Steven Sherman,United States,NaN,NaN,676.0,221367.20
33,972,Renee J Tucker,Matthew Amanda Russell,NaN,NaN,"4835 Martin Path Apt. 275, North Anthonyland, ...",51422.0,63217.04
35,974,Sara W MD,Kelly Charlene Franklin,United States,NaN,BA,48598.0,909387.64
37,977,Gary S Castillo,Bradley Michael Prince,Denmark,NaN,"New Jersey, CZ",NaN,139777.01
41,984,Dr. J Lewis,Renee Jessica Lara Kristen,Congo,NaN,"8626 Christopher Port Apt. 398, Annetteburgh, ...",28129.0,453643.76
44,989,Kara F MD,Renee Robert Garcia,United States,NaN,"90797 Dennis Spring, East Debra, PW 29283",269.0,742269.01
45,991,Megan A Cochran,James Phillips,United States,NaN,"593 Ruth Villages, New Jay, VI 26626",68823.0,414884.53

In [33]:
Search.closeHomophones("Gary")

['Garey', 'Garrey', 'Gary']

In [39]:
df2 = pd.read_csv("unique_people_transactions.csv")

In [43]:
count = int(0.05 * len(df2))
new_list = []
while len(new_list) < count:
    for index, row in df2.iterrows():
        try:
            homophone_name = homophone(row['sender_name'], 'first')
            if homophone_name != row['sender_name']:
                new_list.append(row)
        except ValueError:
            pass

In [45]:
df4 = pd.DataFrame(new_list)

In [46]:
df4

,transaction_id,sender_name,receiver_name,sender_address_full,sender_zipcode,receiver_address_full,receiver_zipcode,transaction_amount
1,2,Michelle Lawson,Brian Yang,"5949 Christine Extension, Bobbyville, PW 91044",NaN,"Arkansas, CU",423.0,25010.76
4,5,Kyle Victor Kelly,Stephanie Erin West,Saint Vincent and the Grenadines,NaN,"778 Joseph Corners Suite 596, Jeremiahfurt, NE...",78115.0,736471.21
7,8,Holly Joshua Delacruz,John Jeremy Carlson,Costa Rica,NaN,"9760 Laura Neck, Danielshaven, MA 53578",5571.0,86938.83
8,9,Tanya Samantha Henry,Ashley Roach,United States,75894,"886 Lisa Forges, Port Todd, ID 60755",76.0,421921.82
10,11,Scott Montgomery,Jason Burke,United States,NaN,"64099 Samuel Center Apt. 648, Port Alyssashire...",6905.0,218637.97
...,...,...,...,...,...,...,...,...
988,989,Kara Fitzgerald MD,Renee Robert Garcia,United States,NaN,"90797 Dennis Spring, East Debra, PW 29283",269.0,742269.01
989,990,Katherine Sullivan,Sheila Joshua Bates,United States,NaN,"9833 Graham Row Suite 568, Patrickport, MA 40016",61252.0,154522.90
990,991,Megan Amanda Cochran,James Phillips,United States,NaN,"593 Ruth Villages, New Jay, VI 26626",68823.0,414884.53
993,994,Kristina Flores,Destiny Nancy Jackson,Pitcairn Islands,NaN,"642 James Lakes Apt. 522, Lake Annaton, MS 00579",6938.0,408115.89
998,999,Steven Barton,Daniel James Young,Tuvalu,NaN,"Vermont, IN",519.0,950555.17