# Entity Resolution on Fake Dataset

Amanda Rodgers

October 24, 2024

In [ ]:
pip install pandas

In [4]:
import pandas as pd

In [8]:
# Load the CSV file into a DataFrame
df = pd.read_csv('/Users/amandarodgers/code/splink_practice/first_initial.csv')

# Display the first few rows of the DataFrame to verify that the data has been loaded correctly
df.head(5)

,transaction_id,sender_name,receiver_name,sender_address_full,sender_zipcode,receiver_address_full,receiver_zipcode,transaction_amount
0,1,Jessica Obrien,Stephanie Morales,Japan,NaN,"4466 Marc Village, Port Joseph, UT 69096",950.0,266977.82
1,2,James Andrews,Elizabeth Mcmahon,NaN,NaN,"900 Webster Street Suite 761, North Mary, TN 8...",718.0,936654.59
2,3,Joseph Ross,Sheryl Pope,"773 Sarah Extension Apt. 571, Williamsbury, NJ...",NaN,"75403 Raymond Flat Apt. 085, Jenniferstad, MD ...",99376.0,648035.39
3,4,Heather Smith,Joanne Smith,United States,NaN,"8302 Hicks Point Apt. 917, Kirkshire, MP 63958",665.0,609131.01
4,5,Anna Elliott,Casey Le,United States,NaN,"1690 Eric Summit Apt. 545, Port Evelyn, IL 08556",NaN,171138.65

In [9]:
df.describe()

       transaction_id  receiver_zipcode  transaction_amount
count     1000.000000        950.000000         1000.000000
mean       500.500000      35720.505263       517967.184030
std        288.819436      33648.960293       288695.225009
min          1.000000          5.000000          405.940000
25%        250.750000        788.500000       266470.872500
50%        500.500000      30501.000000       530603.020000
75%        750.250000      64670.000000       762993.962500
max       1000.000000      99925.000000       999907.830000

In [11]:
print(df.dtypes)

transaction_id             int64
sender_name               object
receiver_name             object
sender_address_full       object
sender_zipcode            object
receiver_address_full     object
receiver_zipcode         float64
transaction_amount       float64
dtype: object